package com.example.flightticketreservationsystem.domains;

import com.amazonaws.services.dynamodbv2.datamodeling.*;

@DynamoDBTable(tableName = "YourTableName")
public class AbstractEntity {

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey  // For auto-generated UUIDs
    private String id;  // Note: String instead of Long

    // Other fields...

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }
}