package com.example.flightticketreservationsystem.domains;

import com.amazonaws.services.dynamodbv2.datamodeling.*;

@DynamoDBTable(tableName = "Reservation")
public class Reservation {

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String id;

    @DynamoDBAttribute
    private boolean checkedIn;

    @DynamoDBAttribute
    private int numberOfBags;

    @DynamoDBAttribute
    @DynamoDBTypeConverted(converter = PassengerConverter.class)
    private Passenger passenger;

    @DynamoDBAttribute
    @DynamoDBTypeConverted(converter = FlightConverter.class)
    private Flight flight;

    // Getters and Setters
    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public boolean isCheckedIn() {
        return checkedIn;
    }

    public void setCheckedIn(boolean checkedIn) {
        this.checkedIn = checkedIn;
    }

    public int getNumberOfBags() {
        return numberOfBags;
    }

    public void setNumberOfBags(int numberOfBags) {
        this.numberOfBags = numberOfBags;
    }

    public Passenger getPassenger() {
        return passenger;
    }

    public void setPassenger(Passenger passenger) {
        this.passenger = passenger;
    }

    public Flight getFlight() {
        return flight;
    }

    public void setFlight(Flight flight) {
        this.flight = flight;
    }

    // Converter for Passenger
    static public class PassengerConverter implements DynamoDBTypeConverter<String, Passenger> {
        @Override
        public String convert(Passenger passenger) {
            // Convert Passenger to JSON string or just store the ID
            return passenger.getId(); // Or use JSON serialization
        }

        @Override
        public Passenger unconvert(String s) {
            // Reconstruct Passenger from JSON or lookup by ID
            Passenger p = new Passenger();
            p.setId(s);
            return p;
        }
    }

    // Converter for Flight
    static public class FlightConverter implements DynamoDBTypeConverter<String, Flight> {
        @Override
        public String convert(Flight flight) {
            return flight.getId(); // Or use JSON serialization
        }

        @Override
        public Flight unconvert(String s) {
            Flight f = new Flight();
            f.setId(s);
            return f;
        }
    }
}