package com.example.flightticketreservationsystem.domains;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import java.util.Set;

@DynamoDBTable(tableName = "User")
public class User {

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String id;

    @DynamoDBAttribute
    private String firstName;

    @DynamoDBAttribute
    private String lastName;

    @DynamoDBIndexHashKey(globalSecondaryIndexName = "EmailIndex")
    @DynamoDBAttribute
    private String email;

    @DynamoDBAttribute
    private String password;

    @DynamoDBAttribute
    @DynamoDBTypeConverted(converter = RoleSetConverter.class)
    private Set<String> roleIds; // Stores role IDs instead of Role objects

    // Getters and Setters
    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getFirstName() {
        return firstName;
    }

    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    public String getLastName() {
        return lastName;
    }

    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public Set<String> getRoleIds() {
        return roleIds;
    }

    public void setRoleIds(Set<String> roleIds) {
        this.roleIds = roleIds;
    }

    // Converter for Role IDs Set
    static public class RoleSetConverter implements DynamoDBTypeConverter<Set<String>, Set<String>> {
        @Override
        public Set<String> convert(Set<String> roleIds) {
            return roleIds;
        }

        @Override
        public Set<String> unconvert(Set<String> roleIds) {
            return roleIds;
        }
    }
}